### ISSUE TITLE
UI: request for feature: having one place to display links that are down

### ISSUE THREAD

**Issue by italovalcy** [kytos-ng/topology#125]
From the network operation perspective, it would be nice if we have one place in Kytos to display the links that are down, as well as interfaces that are enabled but down and switches that are enable but down.

It would also be interesting if we could see interface/links/switches that were not enabled yet (having a way to distinguish from those that were already seen -- i.e., display only the new links that were not approved yet, for instance)

**Comment by viniarck** [comment]
Maybe new issue to also color (red/green) ports or links as status

**Comment by viniarck** [comment]
@HeriLFIU will work on this one

**Comment by HeriLFIU** [comment]
@italovalcy I was brainstorming yesterday with Vinicius and we came up with the idea of utilizing a shortcut such as `CTRL + SHIFT + F` for find/filter or `CTRL + SHIFT + S` for search. To access a new tab that would give filtering options which could then be used to find links that are down and other similar data. I think this is currently the best idea as it would be the simplest and wouldn't interfere with the current structure of the NApps. As Vinicius mentioned, some results can be color-coded, such as the status being up or down being green or red.
I made a quick mockup of how the search function would look like.
<img width="674" alt="Web Mockup" src="https://github.com/kytos-ng/topology/assets/142065709/c35337ec-c823-4cee-a5d2-9d35e8490e52">
In some cases, you may want to see some of the other data within the object you searched for. Because of this, I think the data displayed should be in the form of JSON (because there is so much that it wouldn't fit properly within a single table). This would look similar to how Chrome dev tools display JSON, as seen below.
<img width="263" alt="Data Organization" src="https://github.com/kytos-ng/topology/assets/142065709/bc210a48-0334-481c-b80c-a10be84df207">
The last addition of being able to filter interfaces/links/switches based on approval or viewing could be accomplished with an additional button that would allow you to categorize a switch based on whether it was viewed or approved. Expanding on this feature, maybe it would be cool to add categorizing functionality, where you could create groups and split interfaces/links/switches, based on those groups, but since this data wouldn't be being stored anywhere it would probably reset every time you use the UI, I would have to think of a fix for that.

Would this seem like a good way to implement the new feature/fix the issue?

**Comment by viniarck** [comment]
@HeriLFIU, great idea and nice mock up. I'll leave up to @italovalcy and the Ops team to confirm since they'll be the primary user of this interface, but let me also raise these points for you to think about:

- All network entities like `Switch/Interface/Link` they have common properties such as "`enabled`, `active`, `status`, `status_reason`, `metadata`", maybe we could provide these filters for any entities? and then the advanced options would show up if users want to further only filter for a type of particular entities?
- Regarding displaying as JSON like in accordion like Chrome, I think it's cool, specially since it wouldn't constrain much, and give a bit more of freedom, but regardless if using this approach or table, let's also consider to have scroll options. I'd be onboard with JSON like in accordion.

> but since this data wouldn't be being stored anywhere it would probably reset every time you use the UI.

- Good point. You can potentially also use the broser local storage since this is a front-end filter result. Try to look into it. The default behavior is key here though, maybe it shouldn't store in the browser storage everytime but when users want to pre-set they should be able to store that kind of filter with a name, and then when the filter component gets triggered again it can pre-load any of these "profile" used filters? Since we don't support storing this filter in the back-end at the moment, it should be fair game. One of these filter pre-set "profiles" for instance it could be to filter for any `status === "DOWN"`, which could address the initial request of this feature. This is just a suggestion for you to think about, see if you can come up with something better.

**Comment by HeriLFIU** [comment]
> * All network entities like `Switch/Interface/Link` they have common properties such as "`enabled`, `active`, `status`, `status_reason`, `metadata`", maybe we could provide these filters for any entities? and then the advanced options would show up if users want to further only filter for a type of particular entities?

That sounds good to me, maybe the general search bar could be used, and each general requirement could be separated by a comma, or maybe just move the generic dropdowns outside of the advanced search in general.

> Regarding displaying as JSON like in accordion like Chrome, I think it's cool, specially since it wouldn't constrain much, and give a bit more of freedom, but regardless if using this approach or table, let's also consider to have scroll options. I'd be onboard with JSON like in accordion.

Ok

> Good point. You can potentially also use the broser local storage since this is a front-end filter result. Try to look into it. The default behavior is key here though, maybe it shouldn't store in the browser storage everytime but when users want to pre-set they should be able to store that kind of filter with a name, and then when the filter component gets triggered again it can pre-load any of these "profile" used filters? Since we don't support storing this filter in the back-end at the moment, it should be fair game. One of these filter pre-set "profiles" for instance it could be to filter for any status === "DOWN", which could address the initial request of this feature. This is just a suggestion for you to think about, see if you can come up with something better.

Thank you, that seems like a good fix to me for the issue. Ill research the browser local storage and see what can be done.

**Comment by HeriLFIU** [comment]
As Vinicius mentioned the requirements were changed and aligned on slack. The UI will only display the status of all interfaces, switches, and links, and it is to be kept as clean and simple as possible.

For this the idea of implementing a shortcut that would display the UI was proposed:

`ctrl + shift + s`

The UI would then display only the most essential information such as status, reason, enabled, active, and the switch/link name (it would also fall back to the dpid if the name was not available).

There would be 3 separate tables, one for switches, another for links, and  a third for interfaces, displaying this information.

The amount of objects viewable could also be filtered or possibly ordered based on the received data (status, reason, enabled, active, etc).

**Comment by HeriLFIU** [comment]
I had made a mock up of how the UI would look like and it was agreed to.
The following UI mock up can be seen below:
![image](https://github.com/kytos-ng/topology/assets/142065709/708b530d-70d6-4b26-95ea-6e490ee034ab)

**Comment by HeriLFIU** [comment]
It would also be color coded:

- Green for UP
- Red for DOWN
- Yellow for MAINTENANCE
- Grey for ENABLED=False or Disabled

**Comment by viniarck** [comment]
Awesome. Thanks, Heriberto.
